// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/hello/hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelloProto_SayHello_FullMethodName = "/hello.HelloProto/SayHello"
)

// HelloProtoClient is the client API for HelloProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloProtoClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloProtoClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloProtoClient(cc grpc.ClientConnInterface) HelloProtoClient {
	return &helloProtoClient{cc}
}

func (c *helloProtoClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, HelloProto_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloProtoServer is the server API for HelloProto service.
// All implementations must embed UnimplementedHelloProtoServer
// for forward compatibility.
type HelloProtoServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedHelloProtoServer()
}

// UnimplementedHelloProtoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloProtoServer struct{}

func (UnimplementedHelloProtoServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloProtoServer) mustEmbedUnimplementedHelloProtoServer() {}
func (UnimplementedHelloProtoServer) testEmbeddedByValue()                    {}

// UnsafeHelloProtoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloProtoServer will
// result in compilation errors.
type UnsafeHelloProtoServer interface {
	mustEmbedUnimplementedHelloProtoServer()
}

func RegisterHelloProtoServer(s grpc.ServiceRegistrar, srv HelloProtoServer) {
	// If the following call panics, it indicates UnimplementedHelloProtoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelloProto_ServiceDesc, srv)
}

func _HelloProto_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloProtoServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloProto_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloProtoServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloProto_ServiceDesc is the grpc.ServiceDesc for HelloProto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloProto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloProto",
	HandlerType: (*HelloProtoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloProto_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hello/hello.proto",
}
